TODO List app
Fabriciuos/go_final_project_todolist pull request #2
Opened 2024-11-27 15:52 UTC by Fabriciuos

2024-11-28 12:55 UTC, dirtymew requested changes
Привет Арсений

дал комментарии что поправить

думаю на первую итерацию достаточно будет

вопрос - задания со * планировал делать?

2024-11-28 12:55 UTC, dirtymew commented on cmd/main.go
> +	"Go/iternal/app"
модуль как-то странно называется 

кажется что должен с маленькой буквы и лучше github.com/Fabriciuos/go_final_project_todolist  ...

2024-11-28 12:55 UTC, dirtymew commented on iternal/app/app.go
> +	fmt.Println("Запускаем сервер!")
стоит еще порт напчетать

2024-11-28 12:55 UTC, dirtymew commented on iternal/app/app.go
> +	handlers "Go/iternal/transport/rest"
странная сортировка импортов

принято чтобы сначала были импорты стандартной библиотеку - а у тебя они в конце

2024-11-28 12:55 UTC, dirtymew commented on iternal/database/database.go
> +	db, err := sql.Open("sqlite3", dbFile)
плохое решение нужно переделать

у тебя каждый раз открывается подлючение к бд - а их кол-во ограничено

в задании про посылки можно подсмотреть  как было сделано

2024-11-28 12:55 UTC, dirtymew commented on iternal/database/database.go
> +func GetCountOfTasks() (int, error) {
зачем это не очень понятно

2024-11-28 12:55 UTC, dirtymew commented on iternal/database/database.go
> +	rows, err := db.Query("SELECT * FROM scheduler ORDER BY date")
лучше явно поля указывать а не *

2024-11-28 12:55 UTC, dirtymew commented on iternal/database/database.go
> +	rows, err := db.Query("SELECT * FROM scheduler ORDER BY date")
по заданию нужно ограничить выдачу

2024-11-28 12:55 UTC, dirtymew commented on iternal/database/database.go
> +func GetAllTasks() (*sql.Rows, error) {
плохой интерфейс у методов

ты размазываешь зоны ответственности компонент

примерно так нужно 
func GetAllTasks() ([]*services.Task, error)

2024-11-28 12:55 UTC, dirtymew commented on iternal/database/database.go
> +func UpdateDate(task services.Task) error {
непонятно зачем если есть EditTask

2024-11-28 12:55 UTC, dirtymew commented on iternal/database/database.go
> +func DelTask(id string) error {
зачем если есть DeleteTask?

2024-11-28 12:55 UTC, dirtymew commented on iternal/services/service.go
> +package services
название странное - не отражает того что в пакете

тут нет сервиса.... 

сервисного слоя как такового у тебя нет вообще - если хотел сделать то можно подсмотреть в задании про посылки там есть наметки на сервис

2024-11-28 12:55 UTC, dirtymew commented on iternal/transport/rest/handlers.go
> +	TimeFormat = "20060102"
в друг пакетах обьявлена - стоит где-то в одном месте обьявить

2024-11-28 12:55 UTC, dirtymew commented on iternal/transport/rest/handlers.go
> +	"Go/iternal/services"
уже писал про проблемы с импортами выше - нужно поправить во всем проекте

используй go imports

2024-11-28 12:55 UTC, dirtymew commented on iternal/transport/rest/handlers.go
> +	w.Write(resp)
_ , _ = w.Write(resp)
тут стоит либо явно проигнорировать ошибку или ее логировать

2024-11-28 12:55 UTC, dirtymew commented on iternal/transport/rest/handlers.go
> +func CallError(txt string, w http.ResponseWriter) {
а зачем экспортируемый метод - он где-то еще вне пакета используется?

2024-11-28 12:55 UTC, dirtymew commented on iternal/transport/rest/handlers.go
> +		for rows.Next() {
не вот тут и проблемы о чем уже писал

курсор не закрыт и нужно еще ошибку из rows обработать
http://go-database-sql.org/errors.html

это все нужно делать внутри пакета database

2024-12-05 14:54 UTC, Fabriciuos commented on iternal/database/database.go
> +	db, err := sql.Open("sqlite3", dbFile)
Не очень понимаю как это реализовать с моей структурой, можете показать?

2024-12-05 14:59 UTC, Fabriciuos commented on iternal/database/database.go
> +func GetCountOfTasks() (int, error) {
Чтобы посчитать количество задач, решил просто разделить на две функции получение всех задач и подсчет их количества

2024-12-05 15:29 UTC, merged