Practicum
Fabriciuos/go_final_project_todolist pull request #4
Opened 2024-12-05 15:34 UTC by Fabriciuos

Случайно замержил прошлый пул реквест
https://github.com/Fabriciuos/go_final_project_todolist/pull/2

2024-12-05 15:39 UTC, Fabriciuos commented
Не знаю как интегрировать в свой код открытие базы данных только в начале, можете помочь, пожалуйста

2024-12-05 19:06 UTC, dirtymew commented
> Не знаю как интегрировать в свой код открытие базы данных только в начале, можете помочь, пожалуйста

вот твоя работа 
https://github.com/Fabriciuos/8-sprint/pull/1/files#diff-2873f79a86c0d8b3335cd7731b0ecf7dd4301eb19a82ef7a1cba7589b5252261

вот как в ней органозован storage 

<img width="1268" alt="image" src="https://github.com/user-attachments/assets/f6d67bae-587c-4eba-9833-cb3f17d20bb7">

вот как он инициализируется 

<img width="1315" alt="image" src="https://github.com/user-attachments/assets/e4df7426-6ea6-4b03-aafb-c84b539f999f">

можно просто передать его зависимостью в хендлеры как он передается в сервис в задании про посылки

это самый правильный вариант

не очень хороший вариант - подключение передавать в параметрах функции или хранить в глобальной константе

2024-12-05 19:07 UTC, dirtymew requested changes
Арсений

дал рекомендации см комментарии

2024-12-05 19:07 UTC, dirtymew commented on iternal/database/database.go
> +	rows, err := db.Query("SELECT id, date, title, comment, repeat FROM scheduler ORDER BY date LIMIT 50")
лимит в константу вынести

2024-12-06 10:27 UTC, Fabriciuos commented
Исправил несколько открытий баз данных, можете рассказать почему они ограничены, это съедает большое количество ресурсов или почему?

2024-12-07 01:02 UTC, dirtymew commented
> Исправил несколько открытий баз данных, можете рассказать почему они ограничены, это съедает большое количество ресурсов или почему?

ну все в мире ограничено... 
что касается подключений к бд -  у каждой бд, есть свои ограничения. В основном базы данных в веб сервисах - работают по сети, и эти ограничения связаны с кол-вом сетевых портов, но и не только с этим -  у каждой бд свои особенности. Для sqlite это скорее не применимо - но это учебный проект и стоит учиться хорошим практикам...

также еще есть момент с накладными расходами при инициализации и закрытии соединения, что влияет на скорость обработки запросов

2024-12-07 01:04 UTC, dirtymew approved these changes
Арсений

критичный момент исправлен верно

работу принимаю - обрати внимание не замечания

поздравляю и желаю удачи

2024-12-07 01:04 UTC, dirtymew commented on cmd/main.go
> +	db, err := sql.Open("sqlite3", "project")
это кажется лишним

2024-12-07 01:04 UTC, dirtymew commented on iternal/database/database.go
> +	"github.com/Fabriciuos/go_final_project_todolist/iternal/nextdate"
что-то с форматированием кода - нужно поправить

используй go fmt

2024-12-11 12:23 UTC, merged